### ISSUE TITLE
Generator: migration script copies folders instead of folder contents

### ISSUE THREAD

**Issue by Izook** [AlaskaAirlines/WC-Generator#164]
## Describe the bug

When running the migration script folders are copied over into the new repo instead of folder contents. 

## To Reproduce

1. Create new component
1. Follow steps in http://auro.alaskaair.com/getting-started/developers/generator/upgrade to migrate repo to latest version of generator
1. Look at new repo contents
1. See duplicated folders

## Expected behavior

Folder contents to be copied over instead of folders

## Screenshots

![image](https://user-images.githubusercontent.com/23248722/125137181-0741e100-e0c1-11eb-9652-a192856cb5f2.png)

Migration Commit: https://github.com/AlaskaAirlines/aurolabs-card/commit/76341e3926bbed4273b916768835fe8b721fbee6

## Desktop (please complete the following information):

 - OS: Windows 10

## Additional context

- not as big of a deal but the documentation `auroMigrate.md` mentions that a `upgradeRepo` branch will be created but when I ran the script a `repoUpgrade` branch was created for me.

**Comment by blackfalcon** [comment]
The line in the migration script that does this is 

```bash
command cp -r "${1//\/}"/src/ "${2//\/}"/src
```

The formula this uses is 

```bash
$ cp -r path-to-dir/ path-to-new-dir
```

### Test

Given the following directory

```
├── copied-files
└── files
   └── textDoc.md

directory: 2 file: 1
```

And running this command

```bash
$ cp -r files/ copied-files
```

results with 

```
├── copied-files
|  └── textDoc.md
└── files
   └── textDoc.md

directory: 2 file: 2
```

You can argue that `$ cp -r files/ copied-files/` does the same thing. 

My question is, you are running this on a Windows 10 box. This is a BASH script.I am thinking that Windows directories is the underlying issue here and Auro is not optimized for Windows. Auro [strongly recommends using WSL](http://auro.alaskaair.com/developer-setup/windows) for all auro/node-based development.
