### ISSUE TITLE
Lit 2.0

### ISSUE THREAD

**Issue by blackfalcon** [AlaskaAirlines/WC-Generator#186]
## Is your feature request related to a problem? Please describe.

Update Auro WCs to use lit 2.0

## Describe the solution you'd like

Included in this MAJOR release should be the advancement using lit 2.0 for Auro's HTML custom elements. 

RISK: A question to be answered is, is there an issue with having legacy lit elements with new lit 2.0 elements on the same page? 

## Exit criteria 

- [ ] Review all new lit 2.0 docs to fully understand the scope of the update and communicate any changes that may impact any current assumptions and policies 
- [ ] Test, validate and document any potential issues WCs build with lit 2.0 will have when being presented on a page with WCs built with legacy lit. 
- [ ] Migrate an existing custom element to new lit 2.0 space to smoke-test any potential  issues

**Comment by geoffrich** [comment]
I think this is good to start trying out (maybe try out on a low-risk repo?), but we should wait to convert everything over until Lit 2.0 has a final release. At time of writing, it's still on [2.0.0-rc.2](https://www.npmjs.com/package/lit). There's still a [few open issues](https://github.com/lit/lit/milestone/21) on their milestone tracker.

That being said, the current release is "intended to be feature complete and API stable," so I'm not worried about any significant changes.

Also, does this really need to be a breaking-change for all Auro components? My understanding is that Lit itself has very few breaking changes, mostly in APIs that not many people used. Even if there were breaking changes in Lit, we should be able to keep the breakage internal so that nothing changes for consumers.

**Comment by blackfalcon** [comment]
> Also, does this really need to be a breaking-change for all Auro components? 

That is yet TBD. The real breaking issue here is that we will be fully dropping IE support with this generator. Each component being updated with this new version of the Generator will also be losing IE support. 

It is a band-aid we need to rip off and I don't see any other way to communicate that other than a MAJOR release?

**Comment by geoffrich** [comment]
We'll also need to reference the [upgrade guide](https://lit.dev/docs/releases/upgrade/), especially the list of breaking changes. I didn't see anything we need to worry about on a quick perusal, but we should double check.

**Comment by blackfalcon** [comment]
Updated with this commit 

- https://github.com/AlaskaAirlines/WC-Generator/pull/383/commits/56400c5816c765ffbf4a0f8efba86e5893d27678#diff-4d62358b6f4b985933a16fc493562e0c877aa83736213879215b48bb02cdda41
