### ISSUE TITLE
Update npm build docs scripts to be easier to do

### ISSUE THREAD

**Issue by blackfalcon** [AlaskaAirlines/WC-Generator#328]
## Is your feature request related to a problem? Please describe.

The current npm scrips for local dev are a little cumbersome. 

## Describe the solution you'd like

```
  "scripts": {
    "generate": "node bin/generate.js -n auro-solo -d ../auro-test",
    "build:docs": "node util/generateDocs.js",
    "test": "node bin/generate.js -t -n Han-Solo -P @mypackage -d ./auro-test",
    "sweep": "rm -rf auro-test"
  },
```

**Comment by jason-capsule42** [comment]
I would like to see `build:md` just be `build:docs`. We don't have any docs that aren't md files and and `build:docs` is more descriptive of the action I am looking to do. Any person looking at our script commands will immediately understand `docs` where `md` requires a little understanding.

We should just go with `build:docs` because it's obvious and there is no Auro document not getting built by that command.

**Comment by blackfalcon** [comment]
While I can get on board with what you are suggesting, I don't believe this to always be true. 

> it's obvious and there is no Auro document not getting built by that command.

There are and there will be docs that are not managed via this process.

**Comment by blackfalcon** [comment]
This has been resolved.
