### ISSUE TITLE
wc-generator; improve bundled WCs

### ISSUE THREAD

**Issue by blackfalcon** [AlaskaAirlines/WC-Generator#43]
# User story

As a Developer, I want to be able to use a pre-bundled web component, so I can quickly develop my team's feature without a dynamic front-end.

## Description

The current implementation of the pre-bundled components is using webpack and is less than optimal. The intent was that each bundled asset is independent of the polyfill meaning that the polyfill only needs to be loaded once and then all additional web components could use the same polyfill. 

The polyfill contains Lit element and focus-visible. The web component itself would be responsible for any additional dependency outside of the common dependencies. 

The suggestion is to move away from webpack and use something like rollup or anything that makes this process easier. 

There is also an opportunity to look at what the Web Component Hanger project is doing to deliver all things via a CDN. 

## Players  

* @blackfalcon responsible for specification and replication to all WCs
* @geoffrich providing dev support 
* @gusnaughton providing dev support and insights on Component Hanger CDN solution 
* @tsalright assist with CDN support as the intent is to move away from unpak ad the resource 

## Definition of “Done” (exit criteria)

> The story is generally “done” when the user can complete the outlined task, but make sure to define what that is.

- [ ] Split common dependencies, WC specific dependencies and WC code into appropriate bundles
- [ ] WC must run in a standard static HTML page by only importing JS files 
- [ ] Common dependencies should be in a bundle that is universal between all WCs
- [ ] WC specific dependencies may or may not be bundled with WC code - whatever works best
- [ ] All code to be accessible via a CDN

#### Has been tested in all browsers

- [ ] Chrome
- [ ] Firefox
- [ ] Edge (79 +)
- [ ] Safari
- [ ] Mobile Safari
- [ ] IE11

#### Performance

- [ ] Chrome Lighthhouse report

**Comment by geoffrich** [comment]
Starting to take a look at this today.

**Comment by geoffrich** [comment]
Here's my thoughts on the approach:

- Use Rollup to bundle everything.
- We create two bundles, one for modern browsers and one for legacy, and [use differential serving](https://johnstew.github.io/differential-serving/) to decide which one to use. 
- The legacy bundle includes everything -- babel polyfills, lit-element, focus-visible, whatever. The cost of someone using a legacy browser is that our component file size is really big.
- The modern bundle imports its dependencies from a CDN. This is the only way I could think of to allow dependencies to be shared -- the current strategy of putting everything in a "polyfills" file doesn't work when each component could require different versions of dependencies or different dependencies altogether. 
- I've been experimenting with Skypack as a CDN for testing purposes (e.g. https://cdn.skypack.dev/lit-element?min) but it should work with our own CDN as well.

**Comment by blackfalcon** [comment]
Differential serving was something that we looked at way back when ... but were unable to figure out a strategy. Glad that this is back on the table. 

Skypack is basically the same thing as unpak ... 6, 1/2 dozen of the other. The one thing that I am curious about supporting is versioning. Supported by both unpak and [skypack](https://docs.skypack.dev/lookup-urls/lookup-urls#api-package-matching). 

As far as legacy browser versions, I am ok with packaging this all into a single browser with the webcomponents polyfill as well. Yes, it's super heavy, but that's the tax. 

```
<script nomodule src="/dist/index.legacy.js"></script>
<script type="module" src="/dist/index.esm.js"></script>
```

This is pretty straight forward if we can get this to work! 

If I am understanding this correctly, the idea is that for modern browsers there would be multiple script-tags to import the element itself, then litElement, lit-HTML, and focus-visible, ... individually?

Anything @alaskaairux would have to be packaged with the src WC or would that be from a CDN as well?

**Comment by geoffrich** [comment]
> 
> 
> Differential serving was something that we looked at way back when ... but were unable to figure out a strategy. Glad that this is back on the table.
> 
> Skypack is basically the same thing as unpak ... 6, 1/2 dozen of the other. The one thing that I am curious about supporting is versioning. Supported by both unpak and [skypack](https://docs.skypack.dev/lookup-urls/lookup-urls#api-package-matching).

Skypack seemed to do a better job bundling lit-element when I imported it. It also works with ESM imports out of the box; you have to add `?module` with Unpkg. Unpkg also fires off a bunch more requests (see images below). I'm planning to make versioning a part of it -- hoping to get the version from the package.json and add to the imported URL.

With Skypack:
![image](https://user-images.githubusercontent.com/4992896/96620847-cf89d380-12bc-11eb-8cc1-2f0bbac01b3b.png)

With unpkg:
![image](https://user-images.githubusercontent.com/4992896/96621111-137cd880-12bd-11eb-9358-7d163c750e67.png)

I'm also opening to bundling and hosting these packages ourselves if you think that's important. Skypack only allows 1 million free requests a month per domain, idk if that's an issue.

> As far as legacy browser versions, I am ok with packaging this all into a single browser with the webcomponents polyfill as well. Yes, it's super heavy, but that's the tax.
> 
> ```
> <script nomodule src="/dist/index.legacy.js"></script>
> <script type="module" src="/dist/index.esm.js"></script>
> ```
> 
> This is pretty straight forward if we can get this to work!
> 
> If I am understanding this correctly, the idea is that for modern browsers there would be multiple script-tags to import the element itself, then litElement, lit-HTML, and focus-visible, ... individually?

I'm currently using @rollup/plugin-alias to replace module imports with their CDN equivalent. So `import { LitElement } from 'lit-element'` becomes `import { LitElement } from 'https://cdn.skypack.dev/lit-element?min'` at bundle time. So ideally the consumer doesn't need to manually add these dependencies as script tags, it should happen automatically. This also preserves the normal module import for users who bundle the component themselves.

> Anything @alaskaairux would have to be packaged with the src WC or would that be from a CDN as well?

Right now I'm having CDN delivery for a package be opt-in. There's an array of packages in the Rollup config that we want to load from CDN instead of bundling.

```
const cdnPackages = ['lit-element', 'lit-html', 'focus-visible/dist/focus-visible.min.js'];
```

**Comment by blackfalcon** [comment]
> I'm also opening to bundling and hosting these packages ourselves if you think that's important. Skypack only allows 1 million free requests a month per domain, idk if that's an issue.

I think that the desire is to use internal CDN, but the [pricing](https://www.skypack.dev/pricing/) is reasonable. @tsalright ??

**Comment by blackfalcon** [comment]
> I'm currently using @rollup/plugin-alias to replace module imports with their CDN equivalent. So import { LitElement } from 'lit-element' becomes import { LitElement } from 'https://cdn.skypack.dev/lit-element?min' at bundle time. So ideally the consumer doesn't need to manually add these dependencies as script tags, it should happen automatically. This also preserves the normal module import for users who bundle the component themselves.

Interesting ... when I tried that manually that didn't work. E.g. I updated the import for a WC to be a CDN URL and ran the demo server, that didn't work? Maybe I am missing something?

**Comment by geoffrich** [comment]
I need to play around with it more. I have it working with the starter WC Generator component but something goes awry when you import lit-html directives. Found some issues around it and researching.

**Comment by geoffrich** [comment]
Yeah, so there's an issue with Skypack for lit-html. If you try to load lit-element and lit-html (e.g. importing classMap or isDefined directives), the directives break.  So that's a no-go for now. There's an open issue on their [issue tracker](https://github.com/snowpackjs/skypack-cdn/issues).  If this got fixed, we could theoretically load the component itself through skypack, which would be pretty sweet. 

Here's a demo. The component renders, but anything using a lit-html directive has the function text there for some reason.
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Bundled component test</title>
    <link rel="stylesheet" href="https://unpkg.com/@alaskaairux/orion-design-tokens@latest/dist/tokens/CSSTokenProperties.css" />
    <link rel="stylesheet" href="https://unpkg.com/@alaskaairux/orion-web-core-style-sheets@latest/dist/bundled/baseline.css" />
</head>
<body>
    <auro-button>Click me!</auro-button>
    <script type="module" src="https://cdn.skypack.dev/@alaskaairux/auro-button?min"></script>
</body>
</html>
```

![image](https://user-images.githubusercontent.com/4992896/96799740-ac444e80-13b8-11eb-9c04-9e0c28859fa0.png)

Even with Skypack, we'd still need to provide a bundle for non-module supporting browsers though.

In any event, I'll keep hacking. Going to see if there's a way to bundle lit-element and host ourselves on a CDN. We'd have to figure out how to version it.

**Comment by geoffrich** [comment]
Okay, after some more investigation, I have more thoughts. These are our options:

1. ❌ One bundle with all dependencies supporting all browsers
    - Not good, baseline bundle size would be almost 90K per component
2. ❌ Bundle all dependencies into `polyfills.js` for each component and hope they're identical
    - Current approach, doesn't work well since components have different external dependencies. Even core dependencies like lit-element are on different versions for different components.
2. 🤔 Two bundles, one ES2017 and one ES5. Use differential serving with the module/nomodule trick
    - Easy to implement, but there's some waste as lit-element is bundled with every component
    - Modern bundle baseline would be 29K minified, 7K gzipped per component
    - [Some older browsers would download both bundles](https://gist.github.com/jakub-g/5fc11af85a061ca29cc84892f1059fec)
    - Bundle would be used like so:
```html
<script src="/dist/auro-bundle__bundled.js" type="module"></script>
<script src="https://unpkg.com/@webcomponents/webcomponentsjs@2.4.3/webcomponents-loader.js" nomodule></script>
<script src="/dist/auro-bundle__bundled.es5.js" nomodule></script>
```
3. 🤔 Load everything from module-supporting external CDN to use components
    - CDN needs to support modules so we can take advantage of shared dependencies
    - https://cdn.skypack.dev/@alaskaairux/auro-button?min -- button does not render correctly due to CDN issue with lit-html (screenshot above), fires off 18 requests totaling 60K (38K compressed). 
    - https://jspm.dev/@alaskaairux/auro-button -- button renders correctly, fires off 24 requests totaling 148K (63K compressed)
    - https://unpkg.com/@alaskaairux/auro-button/dist/auro-button.js?module -- button renders correctly, fires off 32 requests totalling 213K (84K compressed). Support for ?module is still experimental so we wouldn't want to rely on this in production.
5. 🤔 Bundle and host shared dependencies ourselves
    - Theoretically we could bundle lit-element ourselves and import from there. That way there wouldn't be duplication in the components.
    - How would we handle versioning (e.g. version in the URL)? That could be tricky to support, especially since we have multiple versions of lit-element. How would we keep the CDN up to date?
6. 🤔 Monorepo e.g. Component Hangar (cc @gusnaughton, let me know if I'm incorrect on any of this)
    - All dependencies and polyfills are bundled into a single file that can be shared between all components
    - Unlike the Component Hanger, we'd need some sort of versioning to prevent breaking changes. Component Hanger doesn't have versioning so that updates to AScom can be pushed whenever. 

## My recommendation

I think we should go with Option 3 (two bundles, one modern and one legacy. Dependencies are bundled per component).

- Straightforward to implement
- Cost is reasonably low for modern browsers (30K/7K baseline per component). It could even be faster than making separate requests for shared dependencies if the consumer is only loading a couple components.
- This shouldn't be the default option. If the consumer cares about duplicating dependencies, they should bundle everything they need themselves. This is intended for environments where the consumer is unable to bundle what they need.
- Consider moving to Skypack once lit-html is supported.

This suggestion would not fulfill the requirement "Common dependencies should be in a bundle that is universal between all WCs." I don't think it's worth the effort right now, and having components on different versions of lit-element makes this trickier. As mentioned above, loading a shared dependency bundle might even make things slower if the consumer only needs a component or two.

Thoughts?

**Comment by blackfalcon** [comment]
> especially since we have multiple versions of lit-element

Is this really an issue? Yes there is a range of v2.2x to v2.4x between components, but it's a trigger for me when I open any component for any update I update lit. That being said, lit has a great track record for not breaking things moving forward. So, I would argue that we could update all the WCs to the same version of lit and we are safe. E.g. each CDN hosted version should also be safe. Yes, if this was a mono-repo there would be no question as all the WCs would be pulling from the same version. 

So, I don't want to move forward with this being a concern larger than it needs to be. 

How does that change your model? I can take the responsibility to update all the WCs to be on the same version of lit if that eases your concerns? I am in the process of moving all the WCs off of Travis, so within the next few days I will be touching ALL WCs. 

> <script src="/dist/auro-bundle__bundled.js" type="module"></script>
> <script src="https://unpkg.com/@webcomponents/webcomponentsjs@2.4.3/webcomponents-loader.js" nomodule></script>
> <script src="/dist/auro-bundle__bundled.es5.js" nomodule></script>

Makes total sense. 

> Some older browsers would download both bundles

I literally don't care. On the record, the user base and revenue is so low from legacy Edge and anything IE, it's not worth our concern for load times.

**Comment by blackfalcon** [comment]
@geoffrich this is AWESOME insight btw! 

![](https://i.giphy.com/media/g9582DNuQppxC/giphy.webp)

**Comment by blackfalcon** [comment]
I am going to bind https://github.com/AlaskaAirlines/WC-Generator/issues/41 to this update as well. If during the bindle refactor we see the opportunity to address this, then do so. 

Regardless, once this issue is closed, https://github.com/AlaskaAirlines/WC-Generator/issues/41 will be closed as well.

**Comment by geoffrich** [comment]
Last week was busy and I haven't had much time to work on this. Hoping to provide another update this week.

**Comment by geoffrich** [comment]
After some more research, I've discovered that bundling lit-element is going to be tricky. When you use a lit-html directive (e.g. classMap), it must be imported from the same place you imported the `html` template function from. This is because lit-html keeps track of which functions are directives, so it knows how to use them. If you don't import from the same place, you get stuff like this: 
![image](https://user-images.githubusercontent.com/4992896/98582669-21989600-2278-11eb-8bd8-94c6bbb874b4.png)

So, if we want to bundle lit-element by itself to use as a shared dependency, we also need to bundle every lit-html directive we might use. If we miss one and we use it, the bundled component breaks. We'd also need to transform the individual directive imports to point to our bundled dependency file.

```js
import { LitElement, html, css } from "lit-element"; // transformed to import { LitElement, html, css } from "./bundled-deps.js";
import { classMap } from 'lit-html/directives/class-map'; // transformed to import { classMap } from "./bundled-deps.js";
```
That seems tricky to accomplish in a resilient way at build time, since it's not just find and replace -- we're transforming an import a couple levels deep into a top-level important.

Component library ends up writing their component files like this instead:
```js
import { LitElement, html, css, classMap, ifDefined } from "./component-base.js";
```

That works for them, but it wouldn't for Auro. Using a component-base file prevents anyone else from bundling this component in a performant way.

My suggestion is that we bundle lit element/html with each individual component for now. Once we have a working bundled version, we can iterate on sharing dependencies better. For now, the 7K gzipped baseline per component isn't bad, especially if the consumer is only using one or two components. If they're using more and really care about performance, they can think about bundling the components for their own use.

@blackfalcon any objections?

**Comment by blackfalcon** [comment]
Great work @geoffrich. This all makes total sense. Like many things, we have come full circle. Where you are going is actually where we began. 

I am all for this direction. I am also assuming that we are dumping webpack for rollup here?

**Comment by geoffrich** [comment]
Yes, I'm using rollup. I have working bundles for modern browsers + IE, adding some polish now. Once that's complete I'll start updating the bundle scaffolding in WC-Generator.

**Comment by geoffrich** [comment]
I've pushed my bundling demo to a repo on my GitHub: https://github.com/geoffrich/auro-bundling-demo

@blackfalcon, I'd like some feedback on it before I move these changes into the generator.
High level overview:
- Two bundles generated using Rollup: auro-bundle__bundled.js for modern browsers and auro-bundle__bundled.es5.js for legacy browsers.
- Bundles include all necessary dependencies (see conversation above). The legacy bundle also includes the web components polyfills.
- Module/nomodule approach used to differentially serve (will be outlined in documentation)
- Browserslist updated to last 2 versions of supported browsers + IE11. Babel uses the list to polyfill the modern and legacy build.
- Modern bundle is 29KB minified, 8KB gzipped. Legacy bundle is 196KB minified, 62KB gzipped. These are baseline bundle sizes for any other component bundled with this config, since the test component is very slim.

**Comment by blackfalcon** [comment]
Please schedule a time for us to review this 1:1. There is a lot here that I am not familiar with and will spin a lot of wheels trying to get my head wrapped around all the things.

**Comment by blackfalcon** [comment]
The team is in agreement with the proposed direction. Wating on PR for final review.

**Comment by geoffrich** [comment]
Hoping to get WC PR ready sometime this week. Early next week at the latest. The sample component is working, but I still need to apply the configuration to the generator boilerplate.
